version: '3.9'
services:
  app:
    image: 'hannahtai/tpi-mid-ecommerce-shopcart'
    ports:
      - '8080:8080'
    volumes:
      - ../config/application-dev-compose.yml:/workspace/BOOT-INF/classes/application-dev.yml
    networks:
      - net
    depends_on:
      - db
  db:
    image: 'postgres:13.3-alpine'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pw123456
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: '2'
    networks:
      - net

networks:
  net:
    driver: bridge