spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: pw123456
  jpa:
    show-sql: true
flyway:
  url: jdbc:postgresql://db:5432/postgres
  user: postgres
  password: pw123456
client:
  url:
    goods: http://18.183.144.77:8080
    order: http://18.183.144.77:8081